### PR TITLE
Fixes initial install, adds authorizer, removes all refs to simple-lock

### PR DESCRIPTION
**Pull request by bangfe**
Several updates:

1. [BUG] - Converted all refs of simple-lock to auth-ember-simple-auth. This was causing the blueprint to not fire and install the deps on initial ember install
1. [ENHANCEMENT] - Added authorizer to scaffold and as generator
1. [UPDATE] - Updated the docs with the correct module path to load custom authenticators and authorizers
1. [UPDATE] - Updated deps to latest release
1. [UPDATE] - Toggled off dev mode in the addon

### CODE REVIEW

**Comment by tehsis** [comment]
Awesome work  @bangfe !
I'm going to test it on my side and let you know

Thank you!

**Comment by brancusi** [comment]
Thanks @tehsis!

**Comment by benschwarz** [comment]
All LGTM.

**Comment by tehsis** [comment]
Great work @brancusi! Thank you!

**Comment by brancusi** [comment]
Thank you guys!

**Pull request merged**
