### PR TITLE
Adds some of the easier tests

### PR DESCRIPTION
**Pull request by artburkart**
This library has a long way to go before it will have acceptable test
coverage, but maybe this PR helps get the ball rolling

### CODE REVIEW

**Comment by brancusi** [comment]
This is great. Thank you for kicking this off. We should get this building in CI don't you think?

How would you go about writing the acceptance tests like:

1. user can login in redirect mode
2. can login in popup mode
3. can relogin after failed attempts

Since lock.js is a bit of a black box from the perspective of this addon.

**Comment by artburkart** [comment]
I can set up travis, if that's useful.

I'm sure there are ways to test the three things you've listed - probably mocking with sinon - but lock.js isn't the only black box for me. I haven't seriously looked into the source code of this addon yet. I'll try to chip away at it. Hopefully others do too.

**Comment by brancusi** [comment]
@artburkart excellent. Yes that would be great if you could setup travis. I don't have admin access to this repo though. I thin they require it right?

**Comment by artburkart** [comment]
Hmmm, I don't think it'll be an issue because this repo is public. It will just be a little awkward because the owner of the CI won't be the owner of the repo.

**Comment by brancusi** [comment]
@artburkart, ya it's strange I can't seem to add the repo to travis, are you able to?

**Comment by artburkart** [comment]
I haven't tried yet, but you're probably right. I think Travis has a hook that needs to be installed so it's triggered on pushes. Which brings me to a question. You've forked the repo, right? We could use your repo as a mirror for running tests (or I could fork if that's preferable) and only merge changes when they pass. It's not ideal.

I have not tried reaching out to Auth0 yet though. Do you think that would be a reasonable first step, or have they been unresponsive?

**Pull request merged**
