### PR TITLE
[Don't merge yet] Redirect Mode

### PR DESCRIPTION
**Pull request by Annyv2**
Updates Lock.js to implement redirect mode. Also updates the way it is called  in routes/application.js  

Probably a new tag should be used.

### CODE REVIEW

**Comment by brancusi** [comment]
Thank you for the work @Annyv2. What do you think about moving the pop up mode options into the config file with the other settings like keys etc. we can maybe just pass the whole hash through to the authenticate call from the config and remove the need for the init.

Also, have you tried switching the callback to fat arrow and get rid of the need for self = this?

Lastly, we really need tests. This is an open call to action to anyone reading, I think this addon could be really great if we could get some test coverage and start moving more quickly on updates. 

Let me know what you think

**Comment by Annyv2** [comment]
Hi @brancusi I didn't quite follow what you said about ` just pass the whole hash through to the authenticate call from the config and remove the need for the init.`, could you explain with a little bit more detail? The reason why I put the init function that calls authenticate again, is because on redirect mode, parseHash and getProfile need to be called after lock finishes and the page reloads. 

I haven't tried switching the callback to fat arrow yet, it's a good idea.

**Comment by brancusi** [comment]
Hi @Annyv2, sorry for the confusing response. Few things first.

1. It appears that the `init` piece will trigger authentication as soon as the user visits the app, even if they have not requested to login. Not sure if this is the behavoir we should have
1. In redirect mode I believe we need to implement a callback route like: `myapp.com/oauth`. I think what we need is a route mixin for that oauth callback handler route. The mixin can then parse the hash and handle another redirect back to the either the original requested route, or the `simple-auth` default route after login.

As for passing in the hash from the  config. If you check the `config>environment`, we could use the 

```js
 ENV['auth0-ember-simple-auth'] = {
    clientID: auth0Config.AUTH0_CLIENT_ID,
    domain: auth0Config.AUTH0_DOMAIN
    lockOptions:  {popup:false, clicked:true, authParams:{scope: 'openid'}}
  }
```

so that we get rid of:

```js
var lockOptions = {popup:false,clicked:false};
```

and instead just pass through:

```js
this.get('session')
   .authenticate('simple-auth-authenticator:lock', SETTINGS_IMPORTED_FROM_CONFIG);
```

This way, the addon will be more flexible as lock.js evolves, we just pass any configuration setting straight through.

If you check the authenticate function in the addon authenticator:

```js
authenticate (options) {
  ...
  this.get('lock').show(options, (err, profile, jwt, accessToken, state, refreshToken) => {
  ...
```

Notice we just pass that object straight in that we get from the `this.get('session').authenticate('simple-auth-authenticator:lock', SETTINGS_IMPORTED_FROM_CONFIG);` call.

I think maybe we don't even need to touch the authenticate method in `addon/authenticators/lock.js`

Instead the redirect route mixin can call `afterAuth` with the parsed data it received:

If you notice the ` this.afterAuth(sessionData).then(response => res(this._setupFutureEvents(response)));`

```js
authenticate (options) {
    return new Ember.RSVP.Promise((res, rej) => {
      this.get('lock').show(options, (err, profile, jwt, accessToken, state, refreshToken) => {
        if (err) {
          rej(err);
        } else {
          var sessionData = { profile, jwt, accessToken, refreshToken };
          this.afterAuth(sessionData).then(response => res(this._setupFutureEvents(response)));
        }
      });
    });
  },
```

We could call that from the theoretical redirect route mixin. I think this warrants a bit more investigation. I also think more tests will help us stay on track at this point, else we can really damage things.

Let me know what you think.

**Comment by Annyv2** [comment]
Hi, @brancusi Yes, it is true, the init function is called as soon as the app starts, and that is to maybe "emulate" what happens in redirect mode in other seed projects, when there is just an app.js file that has these lock, getParse and getProfile functions. The reason why I had to implement it that way is because, in redirect mode, first you call lock, which happens on the login action (hence the clicked variable) and then, after you do so the page reloads and you must do getProfile and parseHash, which happens in the authenticate function called by init. If you see lock.js you'll see that I changed that function with a hash conditional. 

If the user doesn't click "sign in", yes, it will call the authenticate function, but nothing will happen because there would be no hash. 

Agree with the variables from config, it would make it more flexible.

Regarding the route mixin, I would need to research it further. But if we call this function ```uthenticate (options) {
    return new Ember.RSVP.Promise((res, rej) => {
      this.get('lock').show(options, (err, profile, jwt, accessToken, state, refreshToken) => {
        if (err) {
          rej(err);
        } else {
          var sessionData = { profile, jwt, accessToken, refreshToken };
          this.afterAuth(sessionData).then(response => res(this._setupFutureEvents(response)));
        }
      });
    });
  },```

It will be popup mode, because it has the callback function that gets the profile, jwt, etc. Which is why I changed the authenticate function to have 3 different aspects, first just call lock.show(options), then parseHash and then getProfile. Im unsure of how the route mixin could work without modifying that function

**Comment by brancusi** [comment]
Hi @Annyv2, the idea with the callback route mixin would be to replace this piece:

```js
 var hash = this.get('lock').parseHash();
         if (hash) {
...
```

This is trying to determine if we are getting called back from redirect mode. So instead of having this conditional, if we rely on the callback route, when it is triggered, only then do we try to parse the hash since we know we are getting called.

I think to preemptively search for the parsedHash seems less ideal then knowing for sure there should be a hash waiting before looking for one, i.e. we hit a dedicated callback route in ember that will have the hash as query params.

What do you think?

**Comment by Annyv2** [comment]
Hi @brancusi  so, in the end that would have to be moved from the authenticate function, right? I tried to create a particular function for the parseHash and getProfile, but anytime I tried to create a function in lock.js, when I called it, it gave me a `it's not a function` error, which is why I ended up putting everything in the authenticate function. Do you know about it?

**Comment by robguilfoyle** [comment]
Hey guys, thanks so much for working hard on this! I feel icky asking, but has there been any movement on this? ;)

**Comment by brancusi** [comment]
@robguilfoyle, sorry for lagging on this. I know @Annyv2 has been on it.  I've been meaning to dedicate a block of time and work through this but it hasn't happened.

Not sure when this is going to happen.

**Comment by rajibahmed** [comment]
Will this be ever completed and merged? I am looking for this feature for long time 👍

**Comment by mpaktiti** [comment]
Hi @Annyv2 , should we review this PR? I'm asking because of the _don't merge yet_ at the title.

**Comment by Annyv2** [comment]
Lock v10 handles redirect mode by default, so this update is no longer needed.

**Comment by sgasser** [comment]
@Annyv2 when lock v10 will be implemented in this package?

Very soon?

**Pull request closed without merging**
